### ISSUE TITLE
Price will still be rounded to precision of 2

### ISSUE THREAD

**Issue by Puresoft** [aurmil/magento-set-price-precision#6]
Hi, after installing your addin (reset the cache), my shop is rendering 3 decimal places.
But if I set a price of 0.026, in the admin area it still gets roundet to 0.03.

If I transfer the price over the soap service it will also be roundet to 0.03.

Hop you could help me.
(Magento 1.9)

Thanks Robert

**Comment by aurmil** [comment]
hi
I can see the problem (the consequence) but for now, I can't see the cause yet
I will try to look deeper
sorry for that, thanks for pointing it out

**Comment by aurmil** [comment]
just to say I don't forget you ;)
I started working on it
but these days/weeks, I have a lot of work

**Comment by Puresoft** [comment]
OK, thank you, I hope you will get it work.

**Comment by Puresoft** [comment]
Hi, are there any news ?

**Comment by aurmil** [comment]
hi
nope, sorry, still absolutely no free time available

**Comment by navarr** [comment]
I also just encountered this issue.  I am currently investigating.  I will update this ticket and/or submit a pull request.

**Comment by navarr** [comment]
So this issue is caused by Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Price::getEscapedValue (I did some Googling).

There are likely other blocks that implement their own precision.

**Comment by aurmil** [comment]
hello
thanks for taking time to look at this problem and submitting PR, really appreciated
I'll review it (hope this month)
regards
